export const hieClientRespData = [
  {
    resourceType: 'Patient',
    id: 'CR4098636401452-9',
    meta: {
      versionId: '1',
      creationTime: '2025-06-09 11:19:36.963921',
      lastUpdated: '2025-09-15 13:12:55.583802',
      source: 'http://cr-nrb.tiberbu.health',
    },
    originSystem: {
      system: 'SAFARICOM-CONSORTIUM-SANDBOX',
      record_id: '',
    },
    title: 'Mr',
    first_name: 'Christian',
    middle_name: 'Harris',
    last_name: 'Gray',
    gender: 'Female',
    date_of_birth: '1980-06-20',
    place_of_birth: 'NAIROBI',
    person_with_disability: 0,
    citizenship: 'KENYAN',
    kra_pin: 'A078188991V',
    preferred_primary_care_network: '071200000000',
    employment_type: 'Self-Employed',
    domestic_worker_type: '',
    civil_status: 'Divorced',
    identification_type: 'National ID',
    identification_number: '10101010',
    other_identifications: [
      {
        identification_number: 'SHA4098636401452-9',
        identification_type: 'SHA Number',
      },
      {
        identification_number: 'HH4098636401452-9',
        identification_type: 'Household Number',
      },
    ],
    dependants: [
      {
        date_added: '2025-06-09 11:19:36.963921',
        relationship: 'Child',
        total: 1,
        result: [
          {
            resourceType: 'Patient',
            id: 'CR0300484544546-3',
            meta: {
              versionId: '1',
              creationTime: '2025-07-29 10:09:49.525561',
              lastUpdated: '2025-07-29 10:09:49.525561',
              source: 'http://cr-nrb.tiberbu.health',
            },
            originSystem: {
              system: 'AFYANGU-00030',
              record_id: '',
            },
            title: '',
            first_name: 'hilda',
            middle_name: 'test',
            last_name: 'jmeter',
            gender: 'Male',
            date_of_birth: '2025-07-02',
            place_of_birth: '',
            person_with_disability: 0,
            citizenship: '',
            kra_pin: '',
            preferred_primary_care_network: '',
            employment_type: '',
            domestic_worker_type: '',
            civil_status: '',
            identification_type: 'Temporary Dependant ID',
            identification_number: 'CR4098636401452-9-2',
            other_identifications: [
              {
                identification_number: 'SHA0300484544546-3',
                identification_type: 'SHA Number',
              },
              {
                identification_number: 'CR4098636401452-9',
                identification_type: 'Household Number',
              },
            ],
            dependants: [],
            is_alive: 1,
            deceased_datetime: '',
            phone: '',
            biometrics_verified: 0,
            biometrics_score: 0,
            email: '',
            country: '',
            county: 'NAIROBI',
            sub_county: 'STAREHE',
            ward: 'STAREHE',
            village_estate: '',
            building_house_no: '',
            latitude: '',
            longitude: '',
            province_state_country: '',
            zip_code: '',
            identification_residence: '',
            employer_name: '',
            employer_pin: '',
            disability_category: '',
            disability_subcategory: '',
            disability_cause: '',
            in_lawful_custody: '',
            admission_remand_number: '',
            document_uploads: [],
            alternative_contacts: [],
            gross_income: 0,
            gross_income_currency: '',
            postal_address: '',
            estimated_contribution: 0,
            estimated_annual_contribution: 0,
            city: '',
            id_serial: '',
            learning_institution_code: '',
            learning_institution_name: '',
            grade_level: '',
            admission_number: '',
            expected_year_of_graduation: '',
            unconfirmed_dependants: [],
            is_agent: 0,
            agent_id: '',
          },
        ],
      },
      {
        date_added: '2025-06-09 11:19:36.963921',
        relationship: 'Child',
        total: 1,
        result: [
          {
            resourceType: 'Patient',
            id: 'CR4677672274543-3',
            meta: {
              versionId: '1',
              creationTime: '2025-08-19 10:17:36.978231',
              lastUpdated: '2025-08-19 10:17:36.978231',
              source: 'http://cr-nrb.tiberbu.health',
            },
            originSystem: {
              system: 'AFYANGU-00030',
              record_id: '',
            },
            title: '',
            first_name: 'filda',
            middle_name: 'test',
            last_name: 'jmeter2',
            gender: 'Male',
            date_of_birth: '2025-07-02',
            place_of_birth: '',
            person_with_disability: 0,
            citizenship: '',
            kra_pin: '',
            preferred_primary_care_network: '',
            employment_type: '',
            domestic_worker_type: '',
            civil_status: '',
            identification_type: 'Temporary Dependant ID',
            identification_number: 'CR4098636401452-9-6',
            other_identifications: [
              {
                identification_number: 'SHA4677672274543-3',
                identification_type: 'SHA Number',
              },
              {
                identification_number: 'CR4098636401452-9',
                identification_type: 'Household Number',
              },
            ],
            dependants: [],
            is_alive: 1,
            deceased_datetime: '',
            phone: '',
            biometrics_verified: 0,
            biometrics_score: 0,
            email: '',
            country: '',
            county: 'NAIROBI',
            sub_county: 'STAREHE',
            ward: 'STAREHE',
            village_estate: '',
            building_house_no: '',
            latitude: '',
            longitude: '',
            province_state_country: '',
            zip_code: '',
            identification_residence: '',
            employer_name: '',
            employer_pin: '',
            disability_category: '',
            disability_subcategory: '',
            disability_cause: '',
            in_lawful_custody: '',
            admission_remand_number: '',
            document_uploads: [],
            alternative_contacts: [],
            gross_income: 0,
            gross_income_currency: '',
            postal_address: '',
            estimated_contribution: 0,
            estimated_annual_contribution: 0,
            city: '',
            id_serial: '',
            learning_institution_code: '',
            learning_institution_name: '',
            grade_level: '',
            admission_number: '',
            expected_year_of_graduation: '',
            unconfirmed_dependants: [],
            is_agent: 0,
            agent_id: '',
          },
        ],
      },
      {
        date_added: '2025-06-09 11:19:36.963921',
        relationship: 'Child',
        total: 1,
        result: [
          {
            resourceType: 'Patient',
            id: 'CR7417999270872-5',
            meta: {
              versionId: '1',
              creationTime: '2025-09-08 14:49:27.524867',
              lastUpdated: '2025-09-08 14:50:37.287849',
              source: 'http://cr-nrb.tiberbu.health',
            },
            originSystem: {
              system: 'AFYANGU-00030',
              record_id: '',
            },
            title: '',
            first_name: 'OWENS',
            middle_name: 'CHILD',
            last_name: 'KEVIN',
            gender: 'Male',
            date_of_birth: '2025-09-02',
            place_of_birth: '',
            person_with_disability: 0,
            citizenship: '',
            kra_pin: '',
            preferred_primary_care_network: '',
            employment_type: '',
            domestic_worker_type: '',
            civil_status: '',
            identification_type: 'Birth Certificate',
            identification_number: '258085',
            other_identifications: [
              {
                identification_number: 'SHA7417999270872-5',
                identification_type: 'SHA Number',
              },
              {
                identification_number: 'CR4098636401452-9',
                identification_type: 'Household Number',
              },
            ],
            dependants: [],
            is_alive: 1,
            deceased_datetime: '',
            phone: '',
            biometrics_verified: 0,
            biometrics_score: 0,
            email: '',
            country: '',
            county: 'NAIROBI',
            sub_county: 'starehe',
            ward: 'STAREHE',
            village_estate: '',
            building_house_no: '',
            latitude: '',
            longitude: '',
            province_state_country: '',
            zip_code: '',
            identification_residence: '',
            employer_name: '',
            employer_pin: '',
            disability_category: '',
            disability_subcategory: '',
            disability_cause: '',
            in_lawful_custody: '',
            admission_remand_number: '',
            document_uploads: [],
            alternative_contacts: [],
            gross_income: 0,
            gross_income_currency: '',
            postal_address: '',
            estimated_contribution: 0,
            estimated_annual_contribution: 0,
            city: '',
            id_serial: '',
            learning_institution_code: '',
            learning_institution_name: '',
            grade_level: '',
            admission_number: '',
            expected_year_of_graduation: '',
            unconfirmed_dependants: [],
            is_agent: 0,
            agent_id: '',
          },
        ],
      },
      {
        date_added: '2025-06-09 11:19:36.963921',
        relationship: 'Child',
        total: 1,
        result: [
          {
            resourceType: 'Patient',
            id: 'CR6558518554239-3',
            meta: {
              versionId: '1',
              creationTime: '2025-09-08 14:53:00.542412',
              lastUpdated: '2025-09-08 14:53:11.055787',
              source: 'http://cr-nrb.tiberbu.health',
            },
            originSystem: {
              system: 'AFYANGU-00030',
              record_id: '',
            },
            title: '',
            first_name: 'OWENS',
            middle_name: 'HONH',
            last_name: 'ALI',
            gender: 'Male',
            date_of_birth: '2025-09-03',
            place_of_birth: '',
            person_with_disability: 0,
            citizenship: '',
            kra_pin: '',
            preferred_primary_care_network: '',
            employment_type: '',
            domestic_worker_type: '',
            civil_status: '',
            identification_type: 'Birth Certificate',
            identification_number: '8588',
            other_identifications: [
              {
                identification_number: 'SHA6558518554239-3',
                identification_type: 'SHA Number',
              },
              {
                identification_number: 'CR4098636401452-9',
                identification_type: 'Household Number',
              },
            ],
            dependants: [],
            is_alive: 1,
            deceased_datetime: '',
            phone: '',
            biometrics_verified: 0,
            biometrics_score: 0,
            email: '',
            country: '',
            county: 'NAIROBI',
            sub_county: 'starehe',
            ward: 'STAREHE',
            village_estate: '',
            building_house_no: '',
            latitude: '',
            longitude: '',
            province_state_country: '',
            zip_code: '',
            identification_residence: '',
            employer_name: '',
            employer_pin: '',
            disability_category: '',
            disability_subcategory: '',
            disability_cause: '',
            in_lawful_custody: '',
            admission_remand_number: '',
            document_uploads: [],
            alternative_contacts: [],
            gross_income: 0,
            gross_income_currency: '',
            postal_address: '',
            estimated_contribution: 0,
            estimated_annual_contribution: 0,
            city: '',
            id_serial: '',
            learning_institution_code: '',
            learning_institution_name: '',
            grade_level: '',
            admission_number: '',
            expected_year_of_graduation: '',
            unconfirmed_dependants: [],
            is_agent: 0,
            agent_id: '',
          },
        ],
      },
      {
        date_added: '2025-06-09 11:19:36.963921',
        relationship: 'Child',
        total: 1,
        result: [
          {
            resourceType: 'Patient',
            id: 'CR4195287270587-4',
            meta: {
              versionId: '1',
              creationTime: '2025-09-08 15:06:17.067875',
              lastUpdated: '2025-09-08 15:06:17.067875',
              source: 'http://cr-nrb.tiberbu.health',
            },
            originSystem: {
              system: 'AFYANGU-00030',
              record_id: '',
            },
            title: '',
            first_name: 'DURAN',
            middle_name: 'OWEN',
            last_name: 'JOHN',
            gender: 'Male',
            date_of_birth: '2025-09-08',
            place_of_birth: '',
            person_with_disability: 0,
            citizenship: '',
            kra_pin: '',
            preferred_primary_care_network: '',
            employment_type: '',
            domestic_worker_type: '',
            civil_status: '',
            identification_type: 'Birth Certificate',
            identification_number: '45546595948',
            other_identifications: [
              {
                identification_number: 'SHA4195287270587-4',
                identification_type: 'SHA Number',
              },
              {
                identification_number: 'CR4098636401452-9',
                identification_type: 'Household Number',
              },
            ],
            dependants: [],
            is_alive: 1,
            deceased_datetime: '',
            phone: '',
            biometrics_verified: 0,
            biometrics_score: 0,
            email: '',
            country: '',
            county: 'NAIROBI',
            sub_county: 'starehe',
            ward: 'STAREHE',
            village_estate: '',
            building_house_no: '',
            latitude: '',
            longitude: '',
            province_state_country: '',
            zip_code: '',
            identification_residence: '',
            employer_name: '',
            employer_pin: '',
            disability_category: '',
            disability_subcategory: '',
            disability_cause: '',
            in_lawful_custody: '',
            admission_remand_number: '',
            document_uploads: [],
            alternative_contacts: [],
            gross_income: 0,
            gross_income_currency: '',
            postal_address: '',
            estimated_contribution: 0,
            estimated_annual_contribution: 0,
            city: '',
            id_serial: '',
            learning_institution_code: '',
            learning_institution_name: '',
            grade_level: '',
            admission_number: '',
            expected_year_of_graduation: '',
            unconfirmed_dependants: [],
            is_agent: 0,
            agent_id: '',
          },
        ],
      },
      {
        date_added: '2025-06-09 11:19:36.963921',
        relationship: 'Child',
        total: 1,
        result: [
          {
            resourceType: 'Patient',
            id: 'CR2704482932736-2',
            meta: {
              versionId: '1',
              creationTime: '2025-09-09 11:46:36.825641',
              lastUpdated: '2025-09-09 11:46:36.825641',
              source: 'http://cr-nrb.tiberbu.health',
            },
            originSystem: {
              system: 'AFYANGU-00030',
              record_id: '',
            },
            title: '',
            first_name: 'CHRIS',
            middle_name: 'RONALDO',
            last_name: 'KEVIN',
            gender: 'Male',
            date_of_birth: '2025-09-02',
            place_of_birth: '',
            person_with_disability: 0,
            citizenship: '',
            kra_pin: '',
            preferred_primary_care_network: '',
            employment_type: '',
            domestic_worker_type: '',
            civil_status: '',
            identification_type: 'Birth Certificate',
            identification_number: '454545',
            other_identifications: [
              {
                identification_number: 'SHA2704482932736-2',
                identification_type: 'SHA Number',
              },
              {
                identification_number: 'CR4098636401452-9',
                identification_type: 'Household Number',
              },
            ],
            dependants: [],
            is_alive: 1,
            deceased_datetime: '',
            phone: '',
            biometrics_verified: 0,
            biometrics_score: 0,
            email: '',
            country: '',
            county: 'NAIROBI',
            sub_county: 'starehe',
            ward: 'STAREHE',
            village_estate: '',
            building_house_no: '',
            latitude: '',
            longitude: '',
            province_state_country: '',
            zip_code: '',
            identification_residence: '',
            employer_name: '',
            employer_pin: '',
            disability_category: '',
            disability_subcategory: '',
            disability_cause: '',
            in_lawful_custody: '',
            admission_remand_number: '',
            document_uploads: [],
            alternative_contacts: [],
            gross_income: 0,
            gross_income_currency: '',
            postal_address: '',
            estimated_contribution: 0,
            estimated_annual_contribution: 0,
            city: '',
            id_serial: '',
            learning_institution_code: '',
            learning_institution_name: '',
            grade_level: '',
            admission_number: '',
            expected_year_of_graduation: '',
            unconfirmed_dependants: [],
            is_agent: 0,
            agent_id: '',
          },
        ],
      },
    ],
    is_alive: 1,
    deceased_datetime: '',
    phone: '070003281486',
    biometrics_verified: 0,
    biometrics_score: 0,
    email: 'akim@coolpeeps.com',
    country: 'KENYA',
    county: 'NAIROBI',
    sub_county: 'starehe',
    ward: 'STAREHE',
    village_estate: 'KARIOKOR',
    building_house_no: 'HSE56',
    latitude: '',
    longitude: '',
    province_state_country: '',
    zip_code: '',
    identification_residence: '',
    employer_name: 'KNS',
    employer_pin: 'KN509990881',
    disability_category: '',
    disability_subcategory: '',
    disability_cause: '',
    in_lawful_custody: '',
    admission_remand_number: '',
    document_uploads: [],
    alternative_contacts: [
      {
        contact_type: 'Phone',
        contact_id: '+254010101010',
        contact_name: 'HASSAN-TEST-WEB',
        relationship: 'Father',
        remarks: 'Next Of Kin',
      },
    ],
    gross_income: 300000,
    gross_income_currency: 'KES',
    postal_address: '',
    estimated_contribution: 0,
    estimated_annual_contribution: 0,
    city: '',
    id_serial: '',
    learning_institution_code: '',
    learning_institution_name: '',
    grade_level: '',
    admission_number: '',
    expected_year_of_graduation: '',
    unconfirmed_dependants: [],
    is_agent: 0,
    agent_id: '',
  },
];
